name: locobot_jazzy

#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: ..
    dockerfile: docker/dockerfile.arm_jazzy
  image: mast3r-slam:arm64-thor-locobot

  volumes:
    # GUI support
    - $HOME/.Xauthority:/root/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /etc/localtime:/etc/localtime:ro

    # Mount entire project directory
    - ..:/workspace:rw

    # Shared native keyframe tensor cache for cross-robot MASt3R backend
    - ../../shared_native_keyframe_cache:/workspace/shared_native_keyframe_cache:rw

    # udev rules for RealSense
    - /etc/udev/rules.d:/etc/udev/rules.d:ro
    - /run/udev:/run/udev:ro

    # Device access
    - "/dev:/dev"
    - "/dev/shm:/dev/shm"

  environment:
    # - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - QT_X11_NO_MITSHM=1
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - PS1=\[\e[1;34m\][locobot]\[\e[0m\] \w #

  # Network mode for SSH X11 forwarding
  network_mode: host
  ipc: host

  # Container settings
  tty: true
  stdin_open: true
  privileged: true
  stop_grace_period: 1s
  working_dir: /workspace/thor

############################
###   GPU settings       ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]

  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - CUDA_VISIBLE_DEVICES=all

##############################
###   Container Services   ###
##############################
services:
  mast3r_locobot_jazzy:
    <<: [ *common, *gpu ]
    container_name: mast3r_locobot_jazzy
    shm_size: "16g"
    command: [ "/bin/bash" ]
